include colorscheme.conf

font_family IoskeleyMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 21.0

disable_ligatures always

background_opacity 1.00

cursor_shape beam
cursor_blink_interval 0
cursor_trail 0

enable_audio_bell no

confirm_os_window_close 0
remember_window_size no
initial_window_width 80c
initial_window_height 24c
window_padding_width 3

paste_actions no-op
clipboard_control write-clipboard write-primary read-clipboard read-primary
