[[language]]
name = "bash"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c-sharp"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["omnisharp"]

[[language]]
name = "dockerfile"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "go"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "html"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "javascript"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "json"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "lua"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "markdown"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "nix"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "php"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["phpactor"]

[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "qml"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["qmlls"]

[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "toml"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "xml"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "yaml"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "zig"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[language-server.omnisharp]
command = "OmniSharp"
args = ["--languageserver"]

[language-server.phpactor]
command = "phpactor"
args = ["language-server"]

[language-server.qmlls]
command = "qmlls"

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false
