gui:
    border: rounded
    theme:
        activeBorderColor:
            - "#ca9ee6"
            - bold
        inactiveBorderColor:
            - "#626880"
        searchingActiveBorderColor:
            - "#e5c890"
        optionsTextColor:
            - "#c6d0f5"
        selectedLineBgColor:
            - "#414559"
        cherryPickedCommitBgColor:
            - "#51576d"
        cherryPickedCommitFgColor:
            - "#ca9ee6"
        unstagedChangesColor:
            - "#e78284"
        defaultFgColor:
            - "#c6d0f5"
